version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: dockerfile

    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mysql:5.7.22
    restart: always
    env_file:
      - .env
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3306:3306
